from pathlib import Path

CUSTOMER_FILE = 'customers.csv'
PRODUCT_FILE ='product.csv'
ORDERHEADER_FILE = 'orderheader.csv'
ORDERDETAILS_FILE = 'orderdetails.csv'
ROOTPATH = Path('../../../datasets')

CUSTOMER_PATH = ROOTPATH.joinpath(CUSTOMER_FILE)
PRODUCT_PATH = ROOTPATH.joinpath(PRODUCT_FILE)
ORDERHEADER_PATH = ROOTPATH.joinpath(ORDERHEADER_FILE)
ORDERDETAILS_PATH = ROOTPATH.joinpath(ORDERDETAILS_FILE)

CSV_FILES = [CUSTOMER_PATH, PRODUCT_PATH, ORDERHEADER_PATH, ORDERDETAILS_PATH]
